name = "doh-check"
type = "javascript"

account_id = "$CF_ACCOUNT_ID"
workers_dev = true

# 指定构建输出目录
[build]
command = "npm run build"
directory = "./build"

# 指定 Pages 构建输出目录
[site]
bucket = "./build"
entry-point = "."

# 其他可选配置
# vars = { ENV_VAR_NAME = "value" }
